package me.asteroidus.swissgrades.ui.app

import me.asteroidus.swissgrades.domain.model.AssessmentWeight
import me.asteroidus.swissgrades.domain.model.PromotionStatus

internal data class GradeReportText(
    val title: String,
    val unofficialNotice: String,
    val roundedAverage: String,
    val detailedAverage: String,
    val average: String,
    val status: String,
    val promotionPoints: String,
    val basket: String,
    val insufficiencies: String,
    val points: String,
    val optionSubject: String,
    val inBasket: String,
    val notCounted: String,
    val noGrades: String,
    val defaultAssessment: String,
    val notAvailable: String,
    val noDate: String,
    val footer: String,
    val generatedOnTemplate: String,
    val cumulativePeriodTemplate: String,
    val semesterOnePeriodTemplate: String,
    val schoolYearLabels: List<String>,
    val pageTemplate: String,
    val promoted: String,
    val blocked: String,
    val incomplete: String,
    val unavailableStatus: String,
    val fullWeight: String,
    val halfWeight: String,
    val quarterWeight: String,
    val semesterOneShort: String,
    val semesterTwoShort: String
) {
    fun generatedOn(date: String): String = generatedOnTemplate.replace("{date}", date)

    fun period(year: SchoolYear, semester: SchoolSemester): String {
        val template = if (semester == SchoolSemester.SEMESTER_2) {
            cumulativePeriodTemplate
        } else {
            semesterOnePeriodTemplate
        }
        return template.replace("{year}", schoolYearLabels[year.ordinal])
    }

    fun page(number: Int): String = pageTemplate.replace("{page}", number.toString())

    fun status(status: PromotionStatus?): String {
        return when (status) {
            PromotionStatus.PROMOTED -> promoted
            PromotionStatus.BLOCKED -> blocked
            PromotionStatus.INCOMPLETE -> incomplete
            null -> unavailableStatus
        }
    }

    fun weight(weight: AssessmentWeight): String {
        return when (weight) {
            AssessmentWeight.FULL -> fullWeight
            AssessmentWeight.HALF -> halfWeight
            AssessmentWeight.QUARTER -> quarterWeight
        }
    }

    fun semesterShort(semester: SchoolSemester): String {
        return when (semester) {
            SchoolSemester.SEMESTER_1 -> semesterOneShort
            SchoolSemester.SEMESTER_2 -> semesterTwoShort
        }
    }

    companion object {
        fun forLanguage(language: AppLanguage): GradeReportText {
            return when (language) {
                AppLanguage.ENGLISH -> GradeReportText(
                    title = "Personal grade report",
                    unofficialNotice = "Personal document generated by SwissGrades. " +
                        "This is not an official report issued by a school.",
                    roundedAverage = "ROUNDED AVERAGE",
                    detailedAverage = "Detailed average",
                    average = "Average",
                    status = "STATUS",
                    promotionPoints = "PROMOTION POINTS",
                    basket = "BASKET",
                    insufficiencies = "INSUFFICIENCIES",
                    points = "Points",
                    optionSubject = "Option subject",
                    inBasket = "In basket",
                    notCounted = "Not counted in results",
                    noGrades = "No grades for this period",
                    defaultAssessment = "Assessment",
                    notAvailable = "Not available",
                    noDate = "No date",
                    footer = "SwissGrades personal report · Not an official school document",
                    generatedOnTemplate = "Generated on {date}",
                    cumulativePeriodTemplate = "{year} · Cumulative situation S1 + S2",
                    semesterOnePeriodTemplate = "{year} · Semester 1",
                    schoolYearLabels = listOf("First year", "Second year", "Third year"),
                    pageTemplate = "Page {page}",
                    promoted = "Promotion requirements met",
                    blocked = "Promotion blocked",
                    incomplete = "Incomplete",
                    unavailableStatus = "Not calculable yet",
                    fullWeight = "Full grade",
                    halfWeight = "Half grade",
                    quarterWeight = "Quarter grade",
                    semesterOneShort = "S1",
                    semesterTwoShort = "S2"
                )

                AppLanguage.FRENCH -> GradeReportText(
                    title = "Relevé personnel de résultats",
                    unofficialNotice = "Document personnel généré par SwissGrades. " +
                        "Il ne constitue pas un bulletin officiel délivré par un établissement scolaire.",
                    roundedAverage = "MOYENNE ARRONDIE",
                    detailedAverage = "Moyenne détaillée",
                    average = "Moyenne",
                    status = "STATUT",
                    promotionPoints = "POINTS DE PROMOTION",
                    basket = "PANIER",
                    insufficiencies = "INSUFFISANCES",
                    points = "Points",
                    optionSubject = "Option",
                    inBasket = "Dans le panier",
                    notCounted = "Non comptée dans les résultats",
                    noGrades = "Aucune note pour cette période",
                    defaultAssessment = "Évaluation",
                    notAvailable = "Non disponible",
                    noDate = "Sans date",
                    footer = "Relevé personnel SwissGrades · Document scolaire non officiel",
                    generatedOnTemplate = "Généré le {date}",
                    cumulativePeriodTemplate = "{year} · Situation cumulative S1 + S2",
                    semesterOnePeriodTemplate = "{year} · Semestre 1",
                    schoolYearLabels = listOf("Première année", "Deuxième année", "Troisième année"),
                    pageTemplate = "Page {page}",
                    promoted = "Conditions de promotion remplies",
                    blocked = "Promotion bloquée",
                    incomplete = "Incomplet",
                    unavailableStatus = "Pas encore calculable",
                    fullWeight = "Note entière",
                    halfWeight = "Demi-note",
                    quarterWeight = "Quart de note",
                    semesterOneShort = "S1",
                    semesterTwoShort = "S2"
                )
            }
        }
    }
}

internal fun GradeReportSubject.displayName(language: AppLanguage): String {
    return optionChoice?.let(language::optionChoiceLabel) ?: sourceName
}

internal fun GradeReportSubSubject.displayName(language: AppLanguage): String {
    return language.optionSubSubjectLabel(sourceName)
}
